// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/kids-light/KidsHomeCard.tsx": () => import("../components/mockups/kids-light/KidsHomeCard.tsx"),
  "./components/mockups/kids-light/KidsLanding.tsx": () => import("../components/mockups/kids-light/KidsLanding.tsx")
};
